feat: add --fast mode
paulirish/speedline pull request #49
Opened 2017-05-08 23:40 UTC by patrickhulce

This PR changes the progress calculation to optionally skip frames that are between ones that have similar progress toward the target. When enabled, it speeds up processing by about 40% and has minimal impact when not enabled via the shortcut. This also aligns perceptual progress and visual progress by sharing the same computation code and fixes #48 by virtue of the fact that we can't wait for the global min when we only parse some of the JPEGs.

Timings
```sh
( for i in $(seq 10); do; speedline cnn.json --pretty; done; )  55.15s user 4.63s system 98% cpu 1:00.44 total

( for i in $(seq 10); do; speedline cnn.json --pretty --fast; done; )  34.28s user 3.32s system 99% cpu 37.737 total
```

1 - (34/55) = ~38%

2017-05-08 23:48 UTC, pahammad commented
Skipping frames can artificially make the visual jitter (jankiness) go away from the calculations. Please make sure that layout instability effects that perceptual speed index captures aren't sacrificed due to this frame-skipping (technically, this is temporal downsampling).

2017-05-08 23:54 UTC, patrickhulce commented
@pahammad by its nature, the impact on the indexes cannot be avoided as you point out. However, in my experience there are a number of issues with using these metrics to as a signal of layout stability in the first place and frequently I've seen jitter artificially be *rewarded* by speed index rather than punished. Would a warning and tunable threshold address your concerns or are you against including the option at all with these drawbacks?

2017-05-09 00:03 UTC, pahammad commented
I am OK with including the frame-skipping as an option if it comes with appropriate warning when the option is exercised. I am very curious about your sentence: "frequently I've seen jitter artificially be rewarded by speed index rather than punished". Are you referring to the classical (histogram-based) speed index, or are you referring to SSIM based perceptual speed index (PSI) ? If you are referring to PSI in that sentence (where it rewards jitter instead of punishing it), I would love to see an example or two - this is opposite to what I've seen.

2017-05-09 17:11 UTC, patrickhulce commented
@pahammad disclaimer text added and I've filed #50 to discuss layout stability tracking 👍

2017-05-09 17:28 UTC, paulirish requested changes
thanks for doing this. will be a big help.

2017-05-09 17:28 UTC, paulirish commented on test/speed-index.js
> +test('speed indexes calculated for realistic trace with --fast', async t => {
let's also assert that we didn't call getPerceptualProgress, etc on every frame, since that's the essence of this.

2017-05-09 17:28 UTC, paulirish commented on src/speed-index.js
> +		opts && opts.fast ? 5 : 0,
set 5 as a constant above? 

reading this line it's hard to understand what "5" as a "threshold" even means.

2017-05-09 17:28 UTC, paulirish commented on src/speed-index.js
> +		frame => {
extract this and the next fn into named variables

2017-05-09 17:28 UTC, paulirish commented on src/speed-index.js
> +		frame => frame.getProgress() || calculateFrameProgress(frame, initial, target),
maybe not enough coffee, but ... brain hurts. 

this is an expression of `fn1 || fn2` and will be passed in as the `getProgress` parameter. 
when called, the fn1 will evaluate and then return and if that result is falsy then the `fn2` will then run?

is there another way to model this?

2017-05-09 17:28 UTC, paulirish commented on src/speed-index.js
> +			setProgress(frames[i], lowerProgress);
should we also set a property on the frame indicating this value was interpolated? just an idea.

2017-05-09 17:28 UTC, paulirish commented on src/speed-index.js
> +	setProgress(lowerFrame, lowerProgress);
should we just put the `setProgress` call inside of our custom `getProgress` fn?

2017-05-09 17:28 UTC, paulirish commented on src/speed-index.js
> +	if (Math.abs(lowerProgress - upperProgress) < threshold) {
as discussed earlier i'm thinking we might want to threshold on time as well.

```js
const FastMode_FrameProgressDelta = 5;  // units: percent
const FastMode_TimeDelta = 200;   // units: ms
```

wdyt? 
this way we can handle a 5% change over 5 seconds (probably worth inspecting) vs a 5% change over 100ms (not worth it)

2017-05-09 17:42 UTC, patrickhulce commented on src/speed-index.js
> +	setProgress(lowerFrame, lowerProgress);
that seems to breakdown the perf win of differentiating between setting the progress and parsing the jpeg to get progress, no?

2017-05-09 17:51 UTC, patrickhulce commented on src/speed-index.js
> +	if (Math.abs(lowerProgress - upperProgress) < threshold) {
yeah I like it, but it'll likely erase a lot of the perf win if it's just straight up `&&`. In the CNN case, the same exact image is used across ~10s of the trace which accounts for ~30 frames. Thoughts on combining progress and time? 

wdyt of using that fun exponentiation window size function from TTFI?
```
allowable percent change = f(time elapsed in seconds) = 4 * e^(-.69 * t) + 1
f(0) = 4 + 1 = 5% allowed change when elapsed time is 0s
f(1) = 2 + 1 = 3% allowed change when elapsed time is 3s
f(∞) = 0 + 1 = 1% allowed change when elapsed time is very large
```

2017-05-09 17:51 UTC, patrickhulce commented on src/speed-index.js
> +			setProgress(frames[i], lowerProgress);
yeah good plan, make the assertion tests easy too

2017-05-09 17:52 UTC, patrickhulce commented on src/speed-index.js
> +		opts && opts.fast ? 5 : 0,
yup will do

2017-05-09 17:52 UTC, patrickhulce commented on src/speed-index.js
> +		frame => {
done

2017-05-09 22:48 UTC, paulirish commented on src/speed-index.js
> +	setProgress(lowerFrame, lowerProgress);
well i meant we cache the result value and only do the work if necessary.
but admittedly there isn't a nice way to do this with the frame object API.

aiight nevermind.

2017-05-09 22:49 UTC, paulirish commented on src/speed-index.js
> +	if (Math.abs(lowerProgress - upperProgress) < threshold) {
yeah i like that approach.

2017-05-09 23:24 UTC, patrickhulce commented on test/speed-index.js
> +test('speed indexes calculated for realistic trace with --fast', async t => {
done

2017-05-10 04:28 UTC, paulirish commented on src/speed-index.js
> +const FAST_MODE_ALLOWABLE_CHANGE_MAX = 5;
speedline doesnt neccessarily follow the google js style guide.

i'd love to take that opportunity to not caps_lock our constants :)

You good with something like... `fastModeAllowableChangeMax` ?

2017-05-10 04:28 UTC, paulirish commented on src/speed-index.js
> +function calculateFastModeAllowableChange(elapsedTime) {
can we add a few tests for `calculateFastModeAllowableChange` to just to confirm our landmark values give the right results

2017-05-10 04:28 UTC, paulirish commented on cli.js
> +speedIndex(filePath, {fast: cli.flags.fast}).then(function (res) {
let's change this opt property name from `fast` to `fastMode`

2017-05-10 04:28 UTC, paulirish commented on test/speed-index.js
> +	// Ensure we skipped computation of most of the 60 fps frames
loooooooove it

2017-05-10 04:30 UTC, patrickhulce commented on src/speed-index.js
> +const FAST_MODE_ALLOWABLE_CHANGE_MAX = 5;
haha sure

2017-05-10 04:33 UTC, patrickhulce commented on cli.js
> +speedIndex(filePath, {fast: cli.flags.fast}).then(function (res) {
done

2017-05-10 04:42 UTC, patrickhulce commented on src/speed-index.js
> +function calculateFastModeAllowableChange(elapsedTime) {
done

2017-05-10 06:53 UTC, paulirish approved these changes

2017-05-10 06:53 UTC, paulirish commented
changes lgtm but 2 test failures we need to work out.

2017-05-10 16:18 UTC, patrickhulce commented
> changes lgtm but 2 test failures we need to work out.

done

2017-05-11 00:46 UTC, paulirish approved these changes

2017-05-11 00:46 UTC, merged

2017-05-11 01:03 UTC, paulirish commented
speedline@1.2.0 published with this.